### ISSUE TITLE
Make typing and posting controllable

### ISSUE THREAD

**Issue by TimDiekmann** [dsg-bielefeld/slurk#11]

**Comment by TimDiekmann** [comment]
@davidschlangen @fabiang7  We may postpone this until after [version 1.1](https://github.com/dsg-bielefeld/slurk/milestone/1)?

**Comment by davidschlangen** [comment]
I can't quite recall what was meant here, but isn't this just the "block typing" feature -- which is already implemented? I mean, we can stop a player from typing, no?

**Comment by TimDiekmann** [comment]
Hmm, you are probably right.. I'd close this then and if there is something wr have missed here, this will be opened again.
