### ISSUE TITLE
Text in chat area should be wrapped

### ISSUE THREAD

**Issue by davidschlangen** [dsg-bielefeld/slurk#17]
Current state: Text in chat bubble is not word wrapped. Long lines are broken up within words.

Should be: Text should be wrapped only at spaces. Use python textwrap or similar.

**Comment by TimDiekmann** [comment]
Is anyone aware of a good Javascript script for this? This should be handled at client side, since the bubbles may differ in size from client to client.

**Comment by davidschlangen** [comment]
Ah, that makes sense. No, don't know any javascript libraries for that. But I'm sure there is one out there. (With a small 100 MB download / import...)
