### ISSUE TITLE
relative size of areas should be controllable with slider

### ISSUE THREAD

**Issue by davidschlangen** [dsg-bielefeld/slurk#18]
At the moment, the relative sizes of the areas (display, chat history, entry) is fixed. We should at least have an option where the relative size can be changed by dragging the border. (Many web apps allow this for changing the size of panes.)

**Comment by TimDiekmann** [comment]
I assume those border changes should be logged for optimize future layouts?

**Comment by davidschlangen** [comment]
Yes, good idea.
