### ISSUE TITLE
line wrapping in input field

### ISSUE THREAD

**Issue by davidschlangen** [dsg-bielefeld/slurk#270]
Problem: When you type a very long message, the text still stays on one line, and the beginning of the line just scrolls away. (Tested on macos, Safari 16; for the simsim cocobots bot, and the echo bot)

Expected: Text should wrap around at end of line, and the beginning of the line should remain visible. (At least optionally.)

**Comment by sebag90** [comment]
line wrapping in the input field is now implemented
