### ISSUE TITLE
make command prefix character(s) configurable

### ISSUE THREAD

**Issue by davidschlangen** [dsg-bielefeld/slurk#34]
It might be good to allow other characters to mark commands. For example, we thought that for a particular setting, marking comands with # instead of / would be more intuitive for people.

(More concretely, in Nazia's setting that would be
`A belongs to category 1, because it is green. #answer`
instead of 
`\answer A belongs to category 1, because it is green.`   Which shows that here maybe the parsing also needs to be different, as the syntax is not "command argument(s)", but rather that the command follwos the "arguments".)

Solution could be to make the set of  "command indicator characters" a configurable option?

**Comment by davidschlangen** [comment]
On second thought, maybe one could go the Twitter route here and make this a thing between users (or in this case, users and bots) and leave the server out of it? 

The presence of a certain hash tag in a message is something that the bot can test for without being explicitly triggered by the command mechanism.  The bot is being triggered by the normal "message" event in any case.  Commands have the additional property that only the bots that have registered them see them, but here don't need this requirement.

So maybe we want to make a conceptual distinction between _commands_ and _tags_, and let the server only handle the former? @nattari , what do you think?

**Comment by TimDiekmann** [comment]
Actually this should be solved via plugins. Let's take the `send-message.js` plugin:

```javascript {.line-numbers} 
if (text.match("^/")) {
    // parameter: [string]
    submit_command(text.substr(1).split(' '));
    // user: dict, timestamp: int, text: string, private: bool
    display_message(current_user, current_timestamp, text.substr(1), true);
} else if (text.match("^image:")) {
    // image: string, width: int, height: int
    submit_image(text.substr(6), 300, 300);
    // user: dict, timestamp: int, image: string, width: int, height: int, private: bool
    display_image(current_user, current_timestamp, text.substr(6), 300, 300, false);
} else {
    // text: string
    submit_text(text);
    // user: dict, timestamp: int, text: string, private: bool
    display_message(current_user, current_timestamp, text, false);
}
```

If we replace `"^/"` in the first line with `"^#"` we will get this desired behavior

**Comment by davidschlangen** [comment]
Ah, of course. It is already "configurable" in a sense, or rather, it is already even more general. That was fast! :-)

**Comment by TimDiekmann** [comment]
It's rather possible to implement *hashtags* this way. Something like `text.includes("#");` and then use the rest of the string as "command".

**Comment by nattari** [comment]
> On second thought, maybe one could go the Twitter route here and make this a thing between users (or in this case, users and bots) and leave the server out of it?
> 
> The presence of a certain hash tag in a message is something that the bot can test for without being explicitly triggered by the command mechanism. The bot is being triggered by the normal "message" event in any case. Commands have the additional property that only the bots that have registered them see them, but here don't need this requirement.
> 
> So maybe we want to make a conceptual distinction between _commands_ and _tags_, and let the server only handle the former? @nattari , what do you think?

Yes, I also think _commands_ should be handled by the server and _tags_ by the bots who need this particular feature. 
As this is already configurable, we can easily make _tags_ as _commads_ based on how players react to this in my set-up.
