### ISSUE TITLE
HTML tags as plain text 

### ISSUE THREAD

**Issue by nattari** [dsg-bielefeld/slurk#40]
HTML tags passed as plain text in chat as well as display area.

**Comment by davidschlangen** [comment]
Please explain in more detail. Please use standard format: what are you seeing. What do you think you should be seeing. What are steps to reproduce the problem.

**Comment by davidschlangen** [comment]
Also please use the tags.

**Comment by nattari** [comment]
In case of CoLA, while showing instructions to the workers as well asking question in the display area, some part of the text is highlighted. By highlighting, I mean some text is in bold and some in different colors. To do this, I use tags, for instance, <b> some text  </b> and instead changing that part of text to bold, it is shown on the screen as is.

**Comment by TimDiekmann** [comment]
Can you give an example, what is not working? I don't see an issue here.

**Comment by davidschlangen** [comment]
Please write again in standard format. See handbook. There is no issue here so far.

**Comment by nattari** [comment]
The text message shown on the display as well as the chat area contains HTML tags.

This can be reproduced using the following step in _slurk_ :
- Inside multi_bot.py, add the below lines to _on_new_image_public_ function. 
`self.emit('remove_class', {
            'room': data['room']['id'],
            'id': "question",
            'class': "hidden"
        })

        self.emit('set_text', {
            'room': data['room']['id'],
            'id': "question",
            'text': '<b> Welcome to Cola game </b>'
        })`

You would see the _text_ is not rendered as HTML.

The desired result should be to show the text as bold i.e. render the content as HTML.

<img width="1280" alt="screen shot 2019-01-17 at 12 00 21" src="https://user-images.githubusercontent.com/7510353/51315027-86568100-1a51-11e9-81b0-d221030fd741.png">

**Comment by TimDiekmann** [comment]
This was introduced to fix #22. If plain HTML could be injected, you could also inject `<script>` or hijack the current HTML scheme. Wouldn't it be possible to work around this by providing a dedicated header-like tag `<b id="header"></b>`?

**Comment by nattari** [comment]
Tried with the header but doesn't seem to work. 
<img width="635" alt="screen shot 2019-01-20 at 22 16 54" src="https://user-images.githubusercontent.com/7510353/51445077-2980f200-1d01-11e9-9aef-f583a80a1589.png">

**Comment by TimDiekmann** [comment]
What exactly have you tried?

**Comment by nattari** [comment]
I tried to use the header tag as you suggested earlier, `<b id="header"></b>`.
Here is how I did it inside the _multi-bot_:
`self.emit('set_text', {
            'room': data['room']['id'],
            'id': "question",
            'text': '<b id="qhead"> Welcome to Cola game </b>'
        })`

Is this the right way to do it? Or, do I have to make changes in the layout?

**Comment by TimDiekmann** [comment]
We have met since you last comment. Was this solved since then?

**Comment by nattari** [comment]
No, it still exists. Adding the screenshot.
<img width="459" alt="screenshot 2019-02-19 at 17 18 21" src="https://user-images.githubusercontent.com/7510353/53030059-7116ad00-346a-11e9-8c38-639253299f0f.png">

I tried the following:
- [ ] `self.emit('set_text', { 'room': data['room']['id'], 'id': "question", 'text': '<b id="qhead"> Welcome to Cola game </b>' })`

**Comment by TimDiekmann** [comment]
It's not possible to inject HTML in the text page. This was introduced in #23 for fixing #22. You may chose another layout with an additional heading section and set it separatly.
