### ISSUE TITLE
contributors.txt missing

### ISSUE THREAD

**Issue by davidschlangen** [dsg-bielefeld/slurk#63]
There should be a text file in the top level directory with the names of all contributors! (That is, all of our wonderful HiWis.)

**Comment by TimDiekmann** [comment]
Isn't that what [the repository's contributors page](https://github.com/dsg-bielefeld/slurk/graphs/contributors) is for?

**Comment by davidschlangen** [comment]
Good point. But there have also been some non-code contributions by Nikolai, Nazia, and Sina, which aren't reflected in that page. But yeah, that page (contributors.txt) should link to the live page as well (the one you linked above).

**Comment by TimDiekmann** [comment]
Any idea for a specific order?
