### ISSUE TITLE
Open external links in docs in new tab

### ISSUE THREAD

**Issue by TimDiekmann** [dsg-bielefeld/slurk#7]
External links in the documentation should open a new tab. Then it is easier for the user to follow the documentation.

**Comment by TimDiekmann** [comment]
Is there any progress? I couldn't figure out how it works with *.rst*.

**Comment by simeonschuez** [comment]
Maybe that's an approach? 
http://jack.rosenth.al/hacking-docutils.html#external-links-in-new-tabs

**Comment by TimDiekmann** [comment]
Yeah, this could work. Will try it out now!

**Comment by TimDiekmann** [comment]
> Maybe that's an approach?
> http://jack.rosenth.al/hacking-docutils.html#external-links-in-new-tabs

This works like a charm, however it needs Python 3. I updated travis and everything now works as expected. Thank you!
